### ISSUE TITLE
Install panic on DB connectivity interrupt 

### ISSUE THREAD

**Issue by mjudeikis** [Azure/ARO-RP#737]
Need to deep dive:
```
ERRO[2020-05-25T13:21:10+01:00]pkg/install/gatherlogs.go:22 install.(*Installer).gatherFailureLogs() Get https://api-int.lcd9f2cv.v4-eastus.osadev.cloud:6443/apis/config.openshift.io/v1/clusterversions/version: unexpected status code 400  client_principal_name= client_request_id=b4495a66-9e75-11ea-a23e-b46921811e1f component=backend correlation_id= request_id=c823a772-1a5a-4721-9a0f-b6adf445f6fc resource_group=v4-eastus resource_id=/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourcegroups/v4-eastus/providers/microsoft.redhatopenshift/openshiftclusters/mjudeikis resource_name=mjudeikis subscription_id=225e02bc-43d0-43d1-a01a-17e584a4ef69
ERRO[2020-05-25T13:23:19+01:00]pkg/install/gatherlogs.go:22 install.(*Installer).gatherFailureLogs() Get https://api-int.lcd9f2cv.v4-eastus.osadev.cloud:6443/apis/config.openshift.io/v1/clusteroperators: unexpected status code 400  client_principal_name= client_request_id=b4495a66-9e75-11ea-a23e-b46921811e1f component=backend correlation_id= request_id=c823a772-1a5a-4721-9a0f-b6adf445f6fc resource_group=v4-eastus resource_id=/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourcegroups/v4-eastus/providers/microsoft.redhatopenshift/openshiftclusters/mjudeikis resource_name=mjudeikis subscription_id=225e02bc-43d0-43d1-a01a-17e584a4ef69
INFO[2020-05-25T13:23:19+01:00]pkg/backend/openshiftcluster.go:59 backend.(*openShiftClusterBackend).try.func1.1() done                                          client_principal_name= client_request_id=b4495a66-9e75-11ea-a23e-b46921811e1f component=backend correlation_id= duration=2182.659805418 request_id=c823a772-1a5a-4721-9a0f-b6adf445f6fc resource_group=v4-eastus resource_id=/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourcegroups/v4-eastus/providers/microsoft.redhatopenshift/openshiftclusters/mjudeikis resource_name=mjudeikis subscription_id=225e02bc-43d0-43d1-a01a-17e584a4ef69
ERRO[2020-05-25T13:23:19+01:00]pkg/util/recover/recover.go:18 recover.Panic() reflect: call of reflect.Value.Pointer on struct Value  client_principal_name= client_request_id=b4495a66-9e75-11ea-a23e-b46921811e1f component=backend correlation_id= request_id=c823a772-1a5a-4721-9a0f-b6adf445f6fc resource_group=v4-eastus resource_id=/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourcegroups/v4-eastus/providers/microsoft.redhatopenshift/openshiftclusters/mjudeikis resource_name=mjudeikis subscription_id=225e02bc-43d0-43d1-a01a-17e584a4ef69
INFO[2020-05-25T13:23:19+01:00]pkg/util/recover/recover.go:19 recover.Panic() goroutine 6031 [running]:
runtime/debug.Stack(0xc00028ba40, 0x2, 0xc0008574d8)
        /home/mjudeiki/.gvm/gos/go1.13.5/src/runtime/debug/stack.go:24 +0x9d
github.com/Azure/ARO-RP/pkg/util/recover.Panic(0xc00028ba40)
        /home/mjudeiki/go/src/github.com/Azure/ARO-RP/pkg/util/recover/recover.go:19 +0x9a
panic(0x27138e0, 0xc000ad3200)
        /home/mjudeiki/.gvm/gos/go1.13.5/src/runtime/panic.go:679 +0x1b2
reflect.Value.Pointer(0x28360c0, 0xc0002edcc0, 0x99, 0xc0002edcc0)
        /home/mjudeiki/.gvm/gos/go1.13.5/src/reflect/value.go:1462 +0x186
github.com/Azure/ARO-RP/pkg/install.(*Installer).runSteps(0xc004635380, 0x312d740, 0xc000ee9140, 0xc00024f440, 0x11, 0x11, 0x1, 0x180)
        /home/mjudeiki/go/src/github.com/Azure/ARO-RP/pkg/install/install.go:269 +0x3aa
github.com/Azure/ARO-RP/pkg/install.(*Installer).Install(0xc004635380, 0x312d740, 0xc000ee9140, 0xc000c78740, 0xc0000170d0, 0xc000c78c60, 0xc0007ba6f0, 0x30f3180)
        /home/mjudeiki/go/src/github.com/Azure/ARO-RP/pkg/install/install.go:218 +0xfa5
github.com/Azure/ARO-RP/pkg/backend/openshiftcluster.(*Manager).Create(0xc0010846c0, 0x312d740, 0xc000ee9140, 0x0, 0x0)
        /home/mjudeiki/go/src/github.com/Azure/ARO-RP/pkg/backend/openshiftcluster/create.go:325 +0x1a89
github.com/Azure/ARO-RP/pkg/backend.(*openShiftClusterBackend).handle(0xc000010108, 0x312d780, 0xc0000f2000, 0xc00028ba40, 0xc000025d00, 0x0, 0x0)
        /home/mjudeiki/go/src/github.com/Azure/ARO-RP/pkg/backend/openshiftcluster.go:88 +0x62b
github.com/Azure/ARO-RP/pkg/backend.(*openShiftClusterBackend).try.func1(0xc00028ba40, 0xc000010108, 0xc000025d00)
        /home/mjudeiki/go/src/github.com/Azure/ARO-RP/pkg/backend/openshiftcluster.go:62 +0x121
created by github.com/Azure/ARO-RP/pkg/backend.(*openShiftClusterBackend).try
        /home/mjudeiki/go/src/github.com/Azure/ARO-RP/pkg/backend/openshiftcluster.go:49 +0x309  client_principal_name= client_request_id=b4495a66-9e75-11ea-a23e-b46921811e1f component=backend correlation_id= request_id=c823a772-1a5a-4721-9a0f-b6adf445f6fc resource_group=v4-eastus resource_id=/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourcegroups/v4-eastus/providers/microsoft.redhatopenshift/openshiftclusters/mjudeikis resource_name=mjudeikis subscription_id=225e02bc-43d0-43d1-a01a-17e584a4ef69
INFO[2020-05-25T13:23:43+01:00]pkg/frontend/middleware/log.go:106 middleware.Log.func1.1() read request                                  client_principal_name= client_request_id=923a4da6-9e82-11ea-aabe-b46921811e1f component=access correlation_id= request_id=9f8615d7-53a2-4bcd-b2ca-9b319a600911 request_method=GET request_path=/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/providers/microsoft.redhatopenshift/openshiftclusters request_proto=HTTP/1.1 request_remote_addr="127.0.0.1:36630" request_user_agent="python/3.8.2 (Linux-5.6.8-300.fc32.x86_64-x86_64-with-glibc2.2.5) msrest/0.6.9 msrest_azure/0.6.3 azureredhatopenshiftclient/2020-04-30 Azure-SDK-For-Python AZURECLI/2.6.0 (RPM)" subscription_id=225e02bc-43d0-43d1-a01a-17e584a4ef69
INFO[2020-05-25T13:23:43+01:00]pkg/util/clusterdata/clusterdata.go:150 clusterdata.(*bestEffortEnricher).isValidProvisioningState() cluster is in "Creating" provisioning state. Skipping enrichment...  component=frontend

```

**Comment by mjudeikis** [comment]
```
ERRO[2020-05-25T13:58:41+01:00]pkg/install/gatherlogs.go:22 install.(*Installer).gatherFailureLogs() Get https://api-int.lcd9f2cv.v4-eastus.osadev.cloud:6443/apis/config.openshift.io/v1/clusteroperators: unexpected status code 400  client_principal_name= client_request_id=b4495a66-9e75-11ea-a23e-b46921811e1f component=backend correlation_id= request_id=c823a772-1a5a-4721-9a0f-b6adf445f6fc resource_group=v4-eastus resource_id=/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourcegroups/v4-eastus/providers/microsoft.redhatopenshift/openshiftclusters/mjudeikis resource_name=mjudeikis subscription_id=225e02bc-43d0-43d1-a01a-17e584a4ef69
ERRO[2020-05-25T13:58:41+01:00]pkg/backend/openshiftcluster.go:197 backend.(*openShiftClusterBackend).updateAsyncOperation.func1() github.com/Azure/ARO-RP/pkg/install.(*Installer).removeBootstrapIgnition-fm: storage.AccountsClient#ListAccountSAS: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ParentResourceNotFound" Message="Can not perform requested operation on nested resource. Parent resource 'clusteryvbjy' not found."  client_principal_name= client_request_id=b4495a66-9e75-11ea-a23e-b46921811e1f component=backend correlation_id= request_id=c823a772-1a5a-4721-9a0f-b6adf445f6fc resource_group=v4-eastus resource_id=/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourcegroups/v4-eastus/providers/microsoft.redhatopenshift/openshiftclusters/mjudeikis resource_name=mjudeikis subscription_id=225e02bc-43d0-43d1-a01a-17e584a4ef69
INFO[2020-05-25T13:58:42+01:00]pkg/backend/openshiftcluster.go:59 backend.(*openShiftClusterBackend).try.func1.1() done                                          client_principal_name= client_request_id=b4495a66-9e75-11ea-a23e-b46921811e1f component=backend correlation_id= duration=261.770407185 request_id=c823a772-1a5a-4721-9a0f-b6adf445f6fc resource_group=v4-eastus resource_id=/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourcegroups/v4-eastus/providers/microsoft.redhatopenshift/openshiftclusters/mjudeikis resource_name=mjudeikis subscription_id=225e02bc-43d0-43d1-a01a-17e584a4ef69
ERRO[2020-05-25T13:59:15+01:00]pkg/install/gatherlogs.go:22 install.(*Installer).gatherFailureLogs() Get https://api-int.lcd9f2cv.v4-eastus.osadev.cloud:6443/apis/config.openshift.io/v1/clusteroperators: unexpected status code 400  client_principal_name= client_request_id=b4495a66-9e75-11ea-a23e-b46921811e1f component=backend correlation_id= request_id=c823a772-1a5a-4721-9a0f-b6adf445f6fc resource_group=v4-eastus resource_id=/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourcegroups/v4-eastus/providers/microsoft.redhatopenshift/openshiftclusters/mjudeikis resource_name=mjudeikis subscription_id=225e02bc-43d0-43d1-a01a-17e584a4ef69
INFO[2020-05-25T13:59:15+01:00]pkg/backend/openshiftcluster.go:59 backend.(*openShiftClusterBackend).try.func1.1() done                                          client_principal_name= client_request_id=b4495a66-9e75-11ea-a23e-b46921811e1f component=backend correlation_id= duration=2063.911271265 request_id=c823a772-1a5a-4721-9a0f-b6adf445f6fc resource_group=v4-eastus resource_id=/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourcegroups/v4-eastus/providers/microsoft.redhatopenshift/openshiftclusters/mjudeikis resource_name=mjudeikis subscription_id=225e02bc-43d0-43d1-a01a-17e584a4ef69                                                                                                                                                                                                                         
ERRO[2020-05-25T13:59:15+01:00]pkg/util/recover/recover.go:18 recover.Panic() reflect: call of reflect.Value.Pointer on struct Value  client_principal_name= client_request_id=b4495a66-9e75-11ea-a23e-b46921811e1f component=backend correlation_id= request_id=c823a772-1a5a-4721-9a0f-b6adf445f6fc resource_group=v4-eastus resource_id=/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourcegroups/v4-eastus/providers/microsoft.redhatopenshift/openshiftclusters/mjudeikis resource_name=mjudeikis subscription_id=225e02bc-43d0-43d1-a01a-17e584a4ef69                                                                                                                                                                                                                                                                            
INFO[2020-05-25T13:59:15+01:00]pkg/util/recover/recover.go:19 recover.Panic() goroutine 7763 [running]:                                                                                                                                                                         
runtime/debug.Stack(0xc0003421c0, 0x2, 0xc000ef94d8)                                                                                                                                                                                                                            
        /home/mjudeiki/.gvm/gos/go1.13.5/src/runtime/debug/stack.go:24 +0x9d                                                                                                                                                                                                    
github.com/Azure/ARO-RP/pkg/util/recover.Panic(0xc0003421c0)                                                                                                                                                                                                                    
        /home/mjudeiki/go/src/github.com/Azure/ARO-RP/pkg/util/recover/recover.go:19 +0x9a                                                                                                                                                                                      
panic(0x27138e0, 0xc0012785e0)                                                                                                                                                                                                                                                  
        /home/mjudeiki/.gvm/gos/go1.13.5/src/runtime/panic.go:679 +0x1b2                                                                                                                                                                                                        
reflect.Value.Pointer(0x28360c0, 0xc0002ed640, 0x99, 0xc0002ed640)                                                                                                                                                                                                              
        /home/mjudeiki/.gvm/gos/go1.13.5/src/reflect/value.go:1462 +0x186                                                                                                                                                                                                       
github.com/Azure/ARO-RP/pkg/install.(*Installer).runSteps(0xc003316480, 0x312d740, 0xc000f76980, 0xc000234a20, 0x11, 0x11, 0x1, 0x180)                                                                                                                                          
        /home/mjudeiki/go/src/github.com/Azure/ARO-RP/pkg/install/install.go:269 +0x3aa                                                                                                                                                                                         
github.com/Azure/ARO-RP/pkg/install.(*Installer).Install(0xc003316480, 0x312d740, 0xc000f76980, 0xc0011f26c0, 0xc000016f28, 0xc0011f2aa0, 0xc0007ba6f0, 0x30f3180)                                                                                                              
        /home/mjudeiki/go/src/github.com/Azure/ARO-RP/pkg/install/install.go:218 +0xfa5                                                                                                                                                                                         
github.com/Azure/ARO-RP/pkg/backend/openshiftcluster.(*Manager).Create(0xc001084b40, 0x312d740, 0xc000f76980, 0x0, 0x0)                                                                                                                                                         
        /home/mjudeiki/go/src/github.com/Azure/ARO-RP/pkg/backend/openshiftcluster/create.go:325 +0x1a89                                                                                                                                                                        
github.com/Azure/ARO-RP/pkg/backend.(*openShiftClusterBackend).handle(0xc000010108, 0x312d780, 0xc0000f2000, 0xc0003421c0, 0xc0013cb900, 0x0, 0x0)                                                                                                                              
        /home/mjudeiki/go/src/github.com/Azure/ARO-RP/pkg/backend/openshiftcluster.go:88 +0x62b                                                                                                                                                                                 
github.com/Azure/ARO-RP/pkg/backend.(*openShiftClusterBackend).try.func1(0xc0003421c0, 0xc000010108, 0xc0013cb900)                                                                                                                                                              
        /home/mjudeiki/go/src/github.com/Azure/ARO-RP/pkg/backend/openshiftcluster.go:62 +0x121                                                                                                                                                                                 
created by github.com/Azure/ARO-RP/pkg/backend.(*openShiftClusterBackend).try                                                                                                                                                                                                   
        /home/mjudeiki/go/src/github.com/Azure/ARO-RP/pkg/backend/openshiftcluster.go:49 +0x309  client_principal_name= client_request_id=b4495a66-9e75-11ea-a23e-b46921811e1f component=backend correlation_id= request_id=c823a772-1a5a-4721-9a0f-b6adf445f6fc resource_group=v4-eastus resource_id=/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourcegroups/v4-eastus/providers/microsoft.redhatopenshift/openshiftclusters/mjudeikis resource_name=mjudeikis subscription_id=225e02bc-43d0-43d1-a01a-17e584a4ef69 
```
